### ISSUE TITLE
Impulse response

### ISSUE THREAD

**Issue by nowgad** [suzumushi0/SpeakerObjects_binary#1]
Is it possible to modify the plug-in so that you can use your impulse response of the room? 
And thank you so much for taking the time to create this version, even earlier! :)

**Comment by suzumushi0** [comment]
If you need to customize room impulse response, set dimensions of the reverberation room and center of the sphere. Note that it is strongly recommended that the center of the sphere be placed in an asymmetrical position in the reverberation room.
